---
"workspace:shift_focus_right": alt-left
"workspace:new_tab": ctrl-t
"pane_group:navigate_down": alt-s
"terminal:clear_blocks": none
"editor_view:cut_word_left": none
"editor_view:move_backward_one_subword": none
"editor_view:move_to_line_end": ctrl-e
"pane_group:add_right": ctrl-alt-right
"workspace:toggle_warp_drive": ctrl-shift-D
"pane_group:navigate_right": alt-d
"pane_group:navigate_up": alt-w
"pane_group:add_down": ctrl-alt-down
"workspace:show_settings_keyboard_shortcuts_page": ctrl-shift-;
"pane_group:add_up": ctrl-alt-up
"terminal:warpify_subshell": ctrl-shift-U
"pane_group:navigate_left": alt-a
"editor_view:cut_word_right": none
"editor_view:delete": ctrl-w
"editor_view:move_forward_one_subword": none
"editor_view:move_to_line_start": ctrl-a
"pane_group:add_left": ctrl-alt-left
"editor_view:select_all": ctrl-shift-A
"workspace:shift_focus_left": alt-right
